version: '3.8'


services:
  web:
    build:
      target: production
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app
      - /app/__pycache__
    command: python run.py
    ports:
      - "5000:5000"


  pgadmin:
    profiles: []  